version: '3'
services:
  fintechapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/fintechapp
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Aybeniz2021
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:14
    environment:
      POSTGRES_DB: fintechapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aybeniz2021
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: